### ISSUE TITLE
成員介紹頁

### ISSUE THREAD

**Issue by wildskyf** [f2etw/f2etw.github.io#16]
原本的介紹文字被誤會成是 title 了，那邊是介紹文字，所以請各成員補齊自己的介紹文字

**Comment by wildskyf** [comment]
還有介紹文字頁面的設計

**Comment by kidwm** [comment]
另外，大頭照裡面的 img 不要寫 height: auto; 把 height 寫死，不然在載入圖片前無法決定大小，會看到橢圓形。
