### ISSUE TITLE
RWD

### ISSUE THREAD

**Issue by wildskyf** [f2etw/f2etw.github.io#18]
use susy

**Comment by wildskyf** [comment]
1. 做一個 layout.scss (這個檔案不要有 front matter，就可以不被 jekyll 處理)
2. susy 將 layout.scss 轉為 layout.css
3. import layout.css

好處是，想要動 RWD 頁面的人再裝 susy 就好，其他人就可以不用多裝。

**Comment by wildskyf** [comment]
@kidwm 
我突然有點懶得用 susy 寫XD
剛拉了一下感覺不用改太多東西就可以直接完成 RWD 了

**Comment by kidwm** [comment]
這個站的版面本來就不複雜，反正你有學到東西就好
