### ISSUE TITLE
收支紀錄

### ISSUE THREAD

**Issue by kidwm** [f2etw/f2etw.github.io#25]
訂出格式之後用 yaml 或是 json 存放

**Comment by Rplus** [comment]
不考慮用 google form 嗎？

**Comment by kidwm** [comment]
@Rplus 你可以先下手為強啊 XD

**Comment by wildskyf** [comment]
@Rplus 我也覺得連出去感覺不好
在看網頁時突然連到 google form 會有種「噢…好哦」的感覺XD
而且連出去就不能有風格統一的設計了～

**Comment by Rplus** [comment]
to @wi1d5ky，
google form 支援 jsonp， 可以直接拿 data
只是表單格式要開好，不然後續調整比較麻煩

**Comment by wildskyf** [comment]
哦哦哦了解！感謝科普:P

**Comment by wildskyf** [comment]
話說這一個 issue 要等 #54 解完後才 close 嗎？

**Comment by kidwm** [comment]
是吧，我也不曉得他們想怎樣了…
