### ISSUE TITLE
按 facebook 讚按鈕後會破版

### ISSUE THREAD

**Issue by wildskyf** [f2etw/f2etw.github.io#36]
![2015-04-16 23 23 43](https://cloud.githubusercontent.com/assets/6042803/7184425/bbfcce14-e48f-11e4-8d86-25a02bdfb0ae.png)

**Comment by wildskyf** [comment]
順便藉這個 issue 問一下，有沒有什麼方法可以改 facebook 後面的字的顏色
不然感覺會看不太清楚

**Comment by kvzhuang** [comment]
他樣式跟裡面的元素是放在iframe fb的domain 的
應該沒辦法控制。
之後想想有啥好方法解好了

**Comment by kidwm** [comment]
其實我覺得這個按鈕根本不必要啊 XD

直接拿掉算了

**Comment by kvzhuang** [comment]
之後還是需要的，我是想做成對文章點讚或分享的連結
這樣會比較多人分享。
我們目前文章流量
之前很大一塊就是從fb分享的
這對社群經營很有幫助。
之後我會修正好OG

**Comment by kidwm** [comment]
那就放在個別文章裡吧，放在 footer 沒什麼用又不好看。

**Comment by kvzhuang** [comment]
ok 那我再想想怎樣放吧 
還要把文章內容跟title放到og
還有image url...不知道能不能抓到...

**Comment by wi1d5ky** [comment]
因為這個也會讓 RWD 破版，
所以在 827px 以下的寬度我就先隱藏 fb_like 囉～

**Comment by wildskyf** [comment]
我有空的時候就把 Facebook 的按讚按鈕移到 post 哦
og 看要不要另外開一個 issue?
