### ISSUE TITLE
用iPad看成員簡介 沒有置中 

### ISSUE THREAD

**Issue by kvzhuang** [f2etw/f2etw.github.io#37]
在左邊
沒有margin: xxpx auto;

**Comment by wildskyf** [comment]
我記得 ipad 上好像還有很多 bug

**Comment by wildskyf** [comment]
- footer 不 flex
- 動態無法顯示
- (同理，徵才應該也沒辦法)

![photo324243475521447929](https://cloud.githubusercontent.com/assets/6042803/7185180/d9ba871c-e493-11e4-926a-06099acb9462.jpg)

**Comment by kidwm** [comment]
等 iOS 9 說不定就支援了 XD

**Comment by wildskyf** [comment]
幫補圖
![image](https://cloud.githubusercontent.com/assets/6042803/7195115/11ed1344-e4ed-11e4-923f-862757c4176f.jpg)
