### ISSUE TITLE
remove jQuery

### ISSUE THREAD

**Issue by kidwm** [f2etw/f2etw.github.io#57]
use window.fetch() after Firefox 39 be released.

**Comment by wildskyf** [comment]
是要等 39 出了以後再拿掉嗎？

**Comment by kidwm** [comment]
@wi1d5ky 是的，Firefox 39 才有 fetch 可以用

**Comment by wildskyf** [comment]
問一下，safari 上有 fetch 可以用嗎？
因為我現在用 ipad 看就是空的，首頁因為有修過了看起來還好，但徵才職缺就會很奇怪

**Comment by kidwm** [comment]
那你也可以修一下徵才職缺啊 XD
iOS 9 不知道有沒有，等出了之後再測試看看

**Comment by wildskyf** [comment]
這個有空可以來做了～

**Comment by kidwm** [comment]
@wi1d5ky Firefox 39 延期了還沒出啊
