### ISSUE TITLE
關於文章迴響

### ISSUE THREAD

**Issue by wildskyf** [f2etw/f2etw.github.io#61]
在思考要不要加上 [disqus](https://disqus.com) 讓讀者可以在文章下面留言。

**Comment by kidwm** [comment]
我不反對，但討厭管理就是…

**Comment by kvzhuang** [comment]
我先申請好disqus 了
有需要給我email我加入disqus管理員

**Comment by wi1d5ky** [comment]
加我一個吧~
wildsky at wildsky.cc
