### ISSUE TITLE
add contribute page

### ISSUE THREAD

**Issue by kidwm** [f2etw/f2etw.github.io#76]
list websites, browser extensions or other javascript related projects.

**Comment by wildskyf** [comment]
我這個週末有空時來弄！

**Comment by kidwm** [comment]
順便把 navigation 的 active 指示換掉吧，三角形不太好看…

**Comment by wildskyf** [comment]
電腦版背景改變，手機版面換圓形；
圓形仍有點突兀，可能是顏色關係。

**Comment by kidwm** [comment]
手機版還破版…

**Comment by wildskyf** [comment]
我還沒有 RWD 咩XD 要不是現在莫名被斷網我就繼續弄了Orz

**Comment by wildskyf** [comment]
@kidwm 這個要 close 了嗎？ 還是有缺什麼我漏掉的？

**Comment by kidwm** [comment]
把瀏覽器套件也列出來吧，像是新同文堂之類的。

**Comment by wildskyf** [comment]
那個是什麼XDD 應該說，我不知道要列哪些。
你的 Dictionary panel 也要嗎？

**Comment by kidwm** [comment]
要給我自肥的話當然好囉 XD，反正有東西列上去，再加段話請人推薦吧

**Comment by wildskyf** [comment]
丟了兩個上去，剩下 js 的開源專案沒有東西

**Comment by wildskyf** [comment]
@kidwm 這一個 issue 要 close 了嗎？

**Comment by kidwm** [comment]
好，先關掉吧
